### PR TITLE
Remote Device Info

### PR DESCRIPTION
**Pull request by logankimmel**
When checking LLDP info, check for at least 4 fields as not all
columns are required
```
env12ToR1#show lldp remote-device all

LLDP Remote Device Summary

Local
Interface RemID   Chassis ID          Port ID           System Name
--------- ------- ------------------- ----------------- -----------------
Te1/0/2   13      00:0A:F7:06:7C:A0   00:0A:F7:06:7C:A0
Te1/0/13  37      00:0A:F7:4F:D4:40   00:0A:F7:4F:D4:40
Te1/0/14  38      00:0A:F7:4F:D4:44   00:0A:F7:4F:D4:44
Te1/0/17  28      F8:B1:56:76:BA:8D   TenGigabitEthernet 0/11  Dell
Te1/0/18  30      F8:B1:56:76:BB:DD   TenGigabitEthernet 0/12  Dell
Te1/0/25  15      00:0A:F7:23:AE:70   00:0A:F7:23:AE:70
Te1/0/29  18      00:10:18:E7:E4:A0   00:10:18:E7:E4:A0
Te1/0/33  257     00:0A:F7:71:78:D0   00:0A:F7:71:78:D0
Te1/0/48  27      00:01:E8:8B:13:E2   TenGigabitEthernet 1/22
Fo1/0/1   19      F8:B1:56:54:63:9D   Fo1/0/1             env12ToR2
```

### CODE REVIEW

**Comment by ripienaar** [comment]
do we need the same in https://github.com/logankimmel/dell-dell_powerconnect/blob/0e5a43848bc82a3cd405bc4ab25f95043dd9a4b3/lib/puppet_x/dell_powerconnect/possible_facts/base.rb#L307 ?

**Comment by gavin-scott** [comment]
I think so, there are still a couple places using it :-(

**Comment by ripienaar** [comment]
alas, only remembered about it after merging, so need a new pr

**Comment by gavin-scott** [comment]
@logankimmel 's on it!

**Pull request merged**
