### PR TITLE
ASM-6727 Added support needed for adding interfaces to a portchannel

### PR DESCRIPTION
**Pull request by asaenz**
This included improving support for configuring VLANs for the
portchannel as well

### CODE REVIEW

**Comment by asaenz** [comment]
Should be merged with https://github.com/dell-asm/asm-deployer/pull/1680

**Comment by asaenz** [comment]
Will fix the tests for this (and probably add some more), but this is ready for review otherwise.

**Comment by ripienaar** [comment]
@sushilrai does this seem fine?

**Comment by sushilrai** [comment]
+1

**Pull request merged**
